#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: README
#+date: <2021-11-21 Sun>
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.2 (Org mode 9.5)
#+cite_export:
* Introduction
Spyglass is a figure scripting interface branching from
the first two levels of the [[id:a3ae4a0f-c61e-4f47-9006-846a070e1025][matplotlib architecture]], parallel to
pyplot. Spyglass is meant to provide boilerplate pyplot doesn't, but it
is intended to do so properly, conveniently, reliably, and reproducibly.

NOTE: prototype uses pyplot.figure to instantiate backend agnostic
display objects. Ultimately this should become fully parallel to pyplot.

The specific figure renders it is intended to provide are those of the
standard kind used in the manuscripts of the Purdue University
Material Science and Engineering Department's Mannodi Research Group

Each convenience class is intended to enable one-liner data/model
analysis using interactive pyplot scripts. They also retain
compatibility with stateless axes artist methods for the production of fully
refined publication quality figures.
* Curry over Factory
following the terminology of [[https://stackoverflow.com/questions/18284296/matplotlib-using-a-figure-object-to-initialize-a-plot][this stackoverflow answer]], Spyglass is
intended to provide curry-like plot methods that offer control of
their assignment using axes pass-through and who's arguments can be
used to customize labels in standard ways, but provide defaults for
rapid throughput inquiry.
* TODO model evaluation
** NEXT ml regressor parity plots
:STATUSLOG:
- State "NEXT"       from "TODO"       [2021-11-22 Mon 12:13]
:END:
** ga dataset reader
*** Smarter Design:
for multiple plot types callable from the same sort of data that
utilizes similarly constructed classes that are nontheless
specialized, use a superclass with =__init_subclass__()= to pick the
right handler class from the user-facing superclass instantiation
(registry/prefix search style?)
* TODO data space comprehension
** TODO pca biplots
** TODO chemistry domain cross tabulations
** Matminer/Dscribe feature visualization
* TODO animation
* TODO DFT Simulator results extractions
** Spagetti Plots
** DOS plots
** phonon states
** optical spectrum analyzer
* TODO 3d lattice
** supercell visualizer
** cupercell with time evolution
* Usage examples:
#+begin_src python :session :exports both :results none
  import numpy as np
  import pandas as pd
  import matplotlib.pyplot as plt
  import spyglass.EDA
  #+end_src
** Basic EDAfig and interaxes invocation
#+begin_src python :session :exports both :results none  
  eda = spyglass.EDA.EDAFigure

  xy = np.random.random((10,2))
  labels = ["Label for instance #{0}".format(i) for i in np.arange(xy.shape[0])]

  fig, ax = plt.subplots(1,1, FigureClass=eda, subplot_kw={'projection':'interactive'})
  fig.add_button()
  ax.activescatter(xy[:,0], xy[:,1], labels)
  plt.show()
#+end_src
** biplot example
#+begin_src python :session :exports both :results none
  from numpy.random import default_rng
  rng = default_rng()
  intpicks = rng.integers(low=1, high=3, size=12)
  xy = np.random.random((12,12))
  xydf = pd.DataFrame(xy)
  ulabels = ["Label for instance #{0}".format(i) for i in xydf.index]
  clabels = ["cluster #{0}".format(i) for i in intpicks]
  uxydf = pd.concat([xydf, pd.Series(ulabels)], axis=1)
  cxydf = pd.concat([xydf, pd.Series(clabels)], axis=1)

  eda = spyglass.EDA.EDAFigure
  fig, ax = plt.subplots(1,1, FigureClass=eda, subplot_kw={'projection':'interactive'})
  fig.add_button()
  ax.biplot([0,1], uxydf, xydf, dim_labels=None,
            dataspan=slice(0,12))
  plt.show()
#+end_src
** pairty plot example
#+begin_src python :session :exports both :results none 
  xy = np.random.random((8,2))
  y_pred = xy[:,1] + np.random.normal(0, 1, 8)
  labels = ["Label for instance #{0}".format(i) for i in np.arange(xy.shape[0])]
  xyydf = pd.DataFrame([xy, y_pred], index=labels,
                       columns=['in', 'expected', 'out'], dtype=float)
  
  eda = spyglass.EDA.EDAFigure
  fig, ax = plt.subplots(1,1, FigureClass=eda, subplot_kw={'projection':'interactive'})
  fig.add_button()
  #ax.add_diagonal()
  ax.set_aspect(1)
  ax.activescatter(x = all_labels, y = all_predictions, grouplabels = all_members, c = 'green')
  ax.activescatter(x = test_labels, y = test_predictions, grouplabels = test_members, c = 'red')
  plt.show()
#+end_src
** test other styles
*** plot interactively
object oriented and intuitive graph generation calls should be possible
#+begin_src ipython :session :exports both :results raw drawer
  plt.ion()
#+end_src
*** plot noninteractively
#+begin_src ipython :session :exports both :results raw drawer
  
#+end_src
*** plot explicitly
#+begin_src ipython :session :exports both :results raw drawer
  
#+end_src
*** plot implicitly
* COMMENT Future:
Matplotlib offers the option to define custom figure classes.
This might be useful for particular specialty plot kinds like ternary plots?

For a relatively high functioning "figure" entity with predefined gui
behavior and set axes, this custom figure providence is probably too
low level.


